# Wprowadzenie do inżynierii oprogramowania

## Ćwiczenia 1

---

* wprowadzenie
* podstawowe typy danych i operatory
* wyrażenia warunkowe i pętle
* funkcje i moduły
* struktury danych
* Łańcuch znaków
* sekwencyjne typy danych
* wyrażenia logiczne

## Podstawowe typy danych 

---

* typ całkowity (*int*)
* typ zmiennoprzecinkowy (*float*)
* typ zespolony (*complex*)
* typ tekstowy (*str*)
* zmienne są typowane dynamicznie

In [4]:
x = 1   # [zmienna] [operator przypisania] [wartość]
y = 1.0
z = 1j

# drukuj typy zmiennych x, y i z
print type(x), type(y), type(z)
# drukuj typy zmiennych b
print "{} {} {}".format(type(x), type(y), type(z))

<type 'int'> <type 'float'> <type 'complex'>
<type 'int'> <type 'float'> <type 'complex'>


In [5]:
x = y # przypisz zmiennej x wartość zmiennej y

print type(x)

<type 'float'>


## Operacje na liczbach

---

In [6]:
2 + 2 # suma dwóch liczb całkowitych -> liczba całkowita

4

In [7]:
2 + 2.0 # wynikiem tej sumy jest liczba zmiennoprzecinkowa

4.0

In [8]:
5 - 2

3

In [9]:
-5 * 2 

-10

In [10]:
5 / 2 

2

In [11]:
6 / 2 

3

In [12]:
from __future__ import division
print 6/2
print 5/2
print 5//2

3.0
2.5
2


## Operacje na liczbach

---

In [13]:
5 % 2 # reszta z dzielenia (operator modulo)

1

In [14]:
int(2.5) # jawne rzutowanie na int

2

In [15]:
float(1) # jawne rzutowanie na float

1.0

In [16]:
complex(1,1) # liczby zespolone

(1+1j)

In [17]:
1+1j # można wprowadzać na dwa sposoby

(1+1j)

In [18]:
(1+2j).real # część rzeczywista

1.0

In [19]:
(1+2j).imag # część urojona

2.0

## Operacje na liczbach

---

In [20]:
abs(-10) # moduł

10

In [21]:
abs(-2.5)

2.5

In [22]:
abs(1+1j) # moduł liczby zespolonej

1.4142135623730951

```py
(1+1j).conjugate() # sprzężenie liczby zespolonej

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-dd7895e870c6> in <module>()
----> 1 int(1+1j) # rzutowania bez sensu zwrócą błąd

TypeError: can't convert complex to int```

## Operacje na liczbach

---

In [23]:
divmod(10, 3) # para (10 // 3 i 10 % 3)

(3, 1)

In [24]:
pow(2, 3) # pow(a, b) = a^b

8

In [25]:
pow(2, 3.0) # zwróć uwagę na typy

8.0

In [26]:
2 ** 3 # inna wersja a^b

8

In [27]:
1j ** 2 # dla zespolonych też działa

(-1+0j)

## Moduł math

---

In [28]:
import math # import [moduł]

dir (math) # lista dostępnych funkcji

['__doc__',
 '__name__',
 '__package__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'hypot',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'modf',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'trunc']

## Moduł math

---

In [29]:
help(math.floor) # dokumentacja funkcji floor z math

Help on built-in function floor in module math:

floor(...)
    floor(x)
    
    Return the floor of x as a float.
    This is the largest integral value <= x.



In [30]:
help(math.ceil) # zwróć uwagę na: moduł.funkcja

Help on built-in function ceil in module math:

ceil(...)
    ceil(x)
    
    Return the ceiling of x as a float.
    This is the smallest integral value >= x.



## Moduł math

---

In [31]:
int(2.8) # rzutowanie float na int "ucina wszystko po kropce"

2

In [32]:
math.floor(2.8) # tak jak funkcja math.floor

2.0

In [33]:
math.ceil(2.8) # funkcja math.ceil zaokrągla w górę

3.0

In [34]:
math.ceil(2.0000000000000001) # zawsze w górę, chyba że po 16 miejscu po przeciunku będzie się różniło

2.0

## Moduł math

---

In [35]:
import cmath # biblioteka standardowa dla liczb zespolonych

dir(cmath) # porównaj z dir(math), jasne czemu moduł.funkcja?

['__doc__',
 '__name__',
 '__package__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atanh',
 'cos',
 'cosh',
 'e',
 'exp',
 'isinf',
 'isnan',
 'log',
 'log10',
 'phase',
 'pi',
 'polar',
 'rect',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh']

In [53]:
import math
print math.sin(math.pi)
print "{0:.2f}".format(math.sin(math.pi))
import cmath
print cmath.sin(math.pi)
import math as m
print m.sin(3.14)
%precision 3
from math import *
print sin(3.14)
from cmath import *
print sin(3.14)

1.22464679915e-16
0.00
(1.22464679915e-16-0j)
0.00159265291649
0.00159265291649
(0.00159265291649-0j)


## Moduł math

---

In [37]:
cmath.sqrt(-1) # cmath potrafi

1j

```py
math.sqrt(-1) # ale math już nie

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-80-9baf3c39fc4a> in <module>()
----> 1 math.sqrt(-1) # ale math już nie

ValueError: math domain error```

## Typ tekstowy

---

* Python 3 używa domyślnie kodowania *unicode* dla typu *str*
* Dzięki czemu mamy polskie znaki od ręki

```py
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> s = "zażółć gęślą jaźń"
>>> s
'zażółć gęślą jaźń'
>>> 
```

## Typ tekstowy bez *unicode*

---

```py
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> s = "zażółć gęślą jaźń"
>>> s
'za\xc5\xbc\xc3\xb3\xc5\x82\xc4\x87 g\xc4\x99\xc5\x9bl\xc4\x85 ja\xc5\xba\xc5\x84'
>>> 
```

## Typ tekstowy

---

* Literał łańcuchowy można wprowadzić przez:
    * pojedynczy cudzysłów
    ```py
    s = 'zażółć gęślą jaźń'
    ```
    * podwójny cudzysłów
    ```py
    s = "zażółć gęślą jaźń"
    ```
    * potrójny cudzysłów
    ```py
    s = '''zażółć gęślą jaźń'''
    s = """zażółć gęślą jaźń"""
    ```

## Znak ucieczki

---

* zmienia interpretację znaku
* w Pythonie (i prawie zawsze) jest to "\"

```py
print("Ala powiedziała: "Mam kota." ...") # cudzysłów kończy literał

 File "<ipython-input-38-2bf66ab2182a>", line 1
    print("Ala powiedziała: "Mam kota." ...") # cudzysłów kończy literał
                                ^
SyntaxError: invalid syntax```

In [54]:
print("Ala powiedziała: \"Mam kota.\" ...") # chyba że "uciekniemy"

Ala powiedziała: "Mam kota." ...


In [55]:
print('Ala powiedziała: "Mam kota." ...') # kombinacja ' i "

Ala powiedziała: "Mam kota." ...


In [56]:
print("Ala powiedziała: 'Mam kota.' ...") # działa w obie strony

Ala powiedziała: 'Mam kota.' ...


## Wybrane sekewncje specjalne

---

* `\n` - nowa linia
* `\t` - tabulacja
* `\r` - powrót kursora
* `\v` - pionowa 


*(Jupyter nie rozumie `\r`)* 

In [42]:
print("\\n wstawia nową linię.\nNowa linia.") # zwróć uwagę na \\n

\n wstawia nową linię.
Nowa linia.


In [43]:
print("\tTabulacja też się przydaje.") # brak spacji po \t

	Tabulacja też się przydaje.


## *Carriage return*

---

```py
# nowa forma importowania: from [moduł] import [funkcja]
from time import sleep
# alternatywa: import time

# drukujemy liczby od 0 do 100
for i in range(100):
    print(i, end="%\r") # kończąc każdą linię % i carriage return
    sleep(1) # i czekamy sekundę na następną liczbę
    # alternatywa: time.sleep(1)
```

## Długie łancuchy

---

In [44]:
tekst = """Lorem Ipsum jest tekstem stosowanym jako przykładowy
wypełniacz w przemyśle poligraficznym. Został po raz
pierwszy użyty w XV w. przez nieznanego drukarza do
wypełnienia tekstem próbnej książki. Pięć wieków później
zaczął być używany przemyśle elektronicznym,
pozostając praktycznie niezmienionym. Spopularyzował się
w latach 60. XX w. wraz z publikacją arkuszy Letrasetu,
zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym
różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do
realizacji druków na komputerach osobistych, jak Aldus PageMaker
"""

print(tekst)

Lorem Ipsum jest tekstem stosowanym jako przykładowy
wypełniacz w przemyśle poligraficznym. Został po raz
pierwszy użyty w XV w. przez nieznanego drukarza do
wypełnienia tekstem próbnej książki. Pięć wieków później
zaczął być używany przemyśle elektronicznym,
pozostając praktycznie niezmienionym. Spopularyzował się
w latach 60. XX w. wraz z publikacją arkuszy Letrasetu,
zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym
różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do
realizacji druków na komputerach osobistych, jak Aldus PageMaker



# Przykład z przyszłości

In [70]:
import numpy as np # o tej bibliotece dowiecie się później
from io import StringIO # Klasa która tworzy w pamięci plik tekstowy wewnątrz programu (bez fizycznego pliku tekstowego)

'''
Otrzymaliśmy dane:

1 0 0 
2 3 4
1 5 12

Chcemy wczytać je przez proste kopiuj wklej
'''

data = u"""1    0 0
2    3 4
1    5 12"""

file_from_data = StringIO(data)

matrix = np.loadtxt(file_from_data)

print matrix
print matrix[1,1]

[[  1.   0.   0.]
 [  2.   3.   4.]
 [  1.   5.  12.]]
3.0


# Formatowanie tekstu

In [45]:
print "{} {}".format(x,y)
print "{0:.3f} {1:.1f} {1:>10.4f}".format(x,y)
print "{0:.3f} {1:.1f} xxxxxxxxxx".format(x,y)

1.0 1.0
1.000 1.0     1.0000
1.000 1.0 xxxxxxxxxx


In [46]:
# [zmienna] [operator przypisania] [wartość]
# typowanie dynamiczne

n = 10  # liczba całkowita
x = 1.5 # liczba zmiennoprzecinkowa
c = 2j  # liczba zespolona
s = "Python" # łańcuch znaków

## Łańuch znaków

---

* zmienna *str* przechowuje tak naprawdę ciąg znaków
* w którym każdy znak ma określoną pozycję

In [47]:
s = "Python"

s[0] # str[i] -> i-ty znak w ciągu

'P'

In [48]:
s[1] # pierwszy to drugi?

'y'

In [49]:
s[2]

't'

## Indeksowanie

---

* indeksowanie zaczyna się od 0 a kończy na *n-1*, gdzie *n* - długość ciągu

In [50]:
s = "Python"

n = len(s) # długość łańcucha s

print(n)

6


In [51]:
s[n-1] # ostatni element

'n'

```py
s[n] # poza zakresem

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-52-1dea7ae0782c> in <module>()
----> 1 s[n] # poza zakresem

IndexError: string index out of range```

## Wycinki

---

In [71]:
s = "Python"

s[2:4] # elementy od 2 do 3 (czyli "od 3 do 4")

'th'

In [72]:
s[2:] # od indeksu 2 do końca

'thon'

In [73]:
s[:2] # od początku do 1

'Py'

In [74]:
s[2:1000] # nie ma błędu o wyjściu poza zakres

'thon'

## Wycinki z krokiem

---

In [75]:
s = "0123456789"

s[2:8:2] # sekwencja[początek:koniec:krok]

'246'

In [76]:
s[2::3] # od 2 do końca co 3

'258'

In [77]:
s[::2] # od początu do końca co 2

'02468'

## Indeksy ujemne

---

* indeks $-k$ oznacza $n-k$, gdzie $n$ - długość łańcucha

In [78]:
s = "Python"

s[-1] # 6 - 1 = 5 -> ostatni znak

'n'

In [79]:
s[-2] # 6 - 2 = 4 -> przedostatni

'o'

In [80]:
s[-2:] # od 4 do końca -> dwa ostatnie

'on'

In [81]:
s[:-2] # wszystko oprócz dwóch ostatnich

'Pyth'

## Lista (*list*)

---

* sekwencja zmiennych dowolnego typu
* dynamiczny rozmiar
* inicjowana jest:
    * nawiasy kwadratowe
    * jawnie *list([iterable])* (czyli konstruktor klasy *list*)
    * lista składana (*list comprehension*)

## Lista przez [ ]

---

In [85]:
lista = [1, 2, 'a', "Python"]

In [86]:
len(lista) # długość listy

4

In [87]:
lista[0] # pierwszy element listy

1

In [88]:
lista[-1] # ostatni element listy

'Python'

## Lista przez konstruktor

---

In [89]:
lista = list([1,2,3]) # bez sensu, ale można

print(lista)

[1, 2, 3]


In [90]:
lista = list("Python") # można stworzyć listę ze string

print(lista)

['P', 'y', 't', 'h', 'o', 'n']


```py
lista = list(1) # ale już nie z int

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-91-5b92e1b521a9> in <module>()
----> 1 lista = list(1) # ale już nie z int

TypeError: 'int' object is not iterable```

## Lista jako rezultat funkcji

---

In [ ]:
help(str.split)

In [95]:
("Mam dosc ogladania przykladow, komentarzy i kodu").split()

['Mam', 'dosc', 'ogladania', 'przykladow']

In [96]:
("Mam dosc ogladania przykladow, komentarzy i kodu").split(',')

['Mam dosc ogladania przykladow', ' komentarzy i kodu']

## Lista składana

---

In [24]:
lista_slow = ['Mam', 'dosc', 'ogladania', 'przykladow']
[len(x) for x in lista_slow] # Składnia [co zrobić z elementem for element in lista]

[3, 4, 9, 10]

## Krotka (*tuple*)

---

* sekwencja zmiennych dowolnego typu
* stały rozmiar
* inicjowana jest:
    * nawiasy okrągłe
    * ciąg elementów oddzielonych przecinkiem
    * jawnie *tuple([iterable])*

In [97]:
krotka = (1, 2, 3, "Python") # jak lista, ale () zamiast []

print(krotka)

(1, 2, 3, 'Python')


In [98]:
krotka = 1, 2, 3, "Python" # brak nawiasów = tuple

print(krotka)

(1, 2, 3, 'Python')


In [ ]:
lista = list("Python") # lista ze stringa

krotka = tuple(lista)  # krotka z listy

krotka2 = tuple("Python")  # krotka ze stringa

print(lista)
print(krotka)
print(krotka2)

## Lista vs Krotka

---

* krotka ma stały rozmiar a lista jest dynamiczna
* krotka jest "niezmienna" (*immutable*) w przeciwieństwie do listy (*mutable*)
* jeśli sekwencja obiektów jest stała w czasie działania programu, lepiej używać krotek
    * szybsze
    * bezpieczniejsze
    * mogą być kluczami w słowniku *(o słownikach potem)*

In [99]:
lista = [1, 2, 3]

print(lista)

lista[0] = 2

print(lista)

[1, 2, 3]
[2, 2, 3]


## Range

---

* uwaga: w Pythonie 2 *range()* jest funkcją wbudowaną; w Pythonie 3 jest to typ danych (klasa)

In [5]:
x = range(10) # od 0 do 10

print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
x[0] = 1 # range jest immutable

In [ ]:
cyfry = range(0, 10)       # range(początek = 0, koniec) 

'''
Stworz range liczb parzystych i nieparzystych

parzyste = ? # range(początek, koniec, krok)
nieparzyste = ?
'''

print(list(cyfry))
print(list(parzyste))
print(list(nieparzyste))

## Sekwencyjne typy danych

---

* *list* - dynamiczny ciąg zmiennych dowolnego typu
* *tuple* - niezmienniczy ciąg zmiennych dowolnego typu
* *range* - dynamiczny ciąg liczba całkowitych
* *str* - niezmienniczy ciąg znaków
* (dla kompletności) są jeszcze binarne sekwencyjne typy danych: *bytes*, *bytearray*, *memoryview*


# Przykład z przyszłości

In [107]:
import numpy as np

a = np.arange(0,1,0.2)

print a

[ 0.   0.2  0.4  0.6  0.8]


## Operacje na sekwencjach

---

* splot (*concatenation*)

In [110]:
begin = "Python "
middle = "is "
end = "awesome!"

begin + middle + end

'Python is awesome!'

In [111]:
lista = [1, 2, 3, 4]
dodatek = [5, 6, 7, 8]

dodatek + lista # kolejność ma znaczenie

[5, 6, 7, 8, 1, 2, 3, 4]

## Operacje na sekwencjach

---

* mnożenie przez liczbę calkowitą

In [112]:
znak = '-'

znak * 10

'----------'

In [113]:
krotka = (1, 2, 3)

2 * krotka

(1, 2, 3, 1, 2, 3)

## Operacje na sekwencjach

---

* wycinki

In [115]:
lista = [1, 2, 3, "Python"]

lista[:2] # dwa pierwsze

[1, 2]

In [116]:
lista[3][-2:] # dwa ostatnie ostatniego

'on'

## Wspólne funkcje klasowe sekwencji

---

* *index* - indeks pierwszego znalezionego elementu
* *count* - ilość wystąpień elementu

In [121]:
x = [1, 2, 3, 4, 5] * 2

print(x)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [122]:
x.count(4) # liczba 4 pojawia się 2 razy

2

In [123]:
x.index(4) # pierwszy raz dla i=3

3

## Operacje na sekwencjach "zmiennych" (*mutable*)

---

In [13]:
lista = [1, 2, 3]

lista[1] = 4 # zamień wartość drugiego elementu

print(lista)

[1, 4, 3]


In [14]:
lista = [1, 2, 3]

lista[1:2] = [5, 5] # zamień wycinek

print(lista)

[1, 5, 5, 3]


In [15]:
lista = [1, 2, 3]

del lista[1:2] # usuń wycinek

print(lista)

[1, 3]


In [18]:
lista = range(10)

print(lista)

del lista[::2] # usuń co drugi element

print(lista)

print lista.pop() # Weź ostatni element i usuń go z listy

print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]
9
[1, 3, 5, 7]


## Funkcje klasowe sekwencji "zmiennych" (*mutable*)

---

In [131]:
lista = [1, 2, 3, 4, 5]

lista.append(6) # append dodaje element na koniec listy

print(lista)

lista.append([7, 8, 9]) # lista dodana jako element

print(lista)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, [7, 8, 9]]


In [11]:
lista = [1, 2, 3, 4, 5]

lista.extend([6, 7, 8, 9]) # extend rozwija listę 

print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [134]:
lista = [1, 2, 3]

lista.insert(1, 4) # wstaw 4 pod indeks 2

print(lista)

[1, 4, 2, 3]


In [25]:
lista = ['a', 'b', 3] * 3

print(lista)

lista.remove('b') # usuń element (pierwsze wystąpienie)

print(lista)

['a', 'b', 3, 'a', 'b', 3, 'a', 'b', 3]
['a', 3, 'a', 'b', 3, 'a', 'b', 3]


In [ ]:
lista = [1, 2, 3]

lista.reverse() # odwróć kolejność

print(lista)

## Funkcja *sort* - tylko dla list

In [12]:
lista = ['e', 'D', 'a', 'b', 'C']

lista.sort() # sortuj 

print(lista)

lista.sort(key=str.lower) # sortuj wg funkcji key

print(lista)

['C', 'D', 'a', 'b', 'e']
['a', 'b', 'C', 'D', 'e']


## Typ logiczny (boolowski, *boolean*)

---

* przyjmuje wartości: prawda lub fałsz
* w Pythonie następujące wartości są utożsamiane z fałszem:
    * False
    * None
    * zero dowolnego typu (0, 0.0, 0j)
    * pusta sekwencja '', (), [] lub mapowanie {}
* pozostałe wartości uznawane są za prawdę

In [20]:
x = 1     # zmiennej x przypisz wartość 1
y = 2     # zmiennej y przypisz wartość 2
False = 3 # zmiennej False przypusz wartość 3

In [136]:
import keyword
print(keyword.kwlist) # lista słów kluczowych w Pythonie

['and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'exec', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'not', 'or', 'pass', 'print', 'raise', 'return', 'try', 'while', 'with', 'yield']


## Dygresja - niedozwolone nazwy zmiennych

---

* słowa kluczowe
* zaczynające się od cyfry
* zawierające polskie znaki
* zawierające cokolwiek innego niż litery, cyfry i `_`

## Porównania

---

| Operacja | Znaczenie |
|:--------:|:---------:|
| ==       | równe     |
| !=       | różne     |
| <        | mniejsze  |
| >        | większe   |
| <=       | mniejsze lub równe |
| >=       | większe lub równe  |
| is       | ten sam identyfikator |
| is not   | inny identyfikator |

## Porównania
---

In [137]:
1 > 0 # większy niż

True

## Mutable vs Immutable
---

* immutable: int, float, complex, str, tuple, (frozen set, bytes)
    * przypisanie zmiennej nowej wartości tworzy nowy obiekt w pamięci
* mutable: list, (set, dict, byte array)
    * możliwa modyfikacja obiektu

---

## Konsekwencje

---

In [22]:
x = 2 # uwtórz obiekt typu int
y = x # y wskazuje na to samo co x

y = 5 # zmieniam y - nowe miejsce w pamięci

print(x) # x dalej wskazuje na 2
print(id(x),id(y))

2
(54814112L, 54814040L)


In [142]:
x = [1, 2, 3] # utwórz obiekt typu list
y = x # y wskazuje na to samo co x

print(id(x), id(y))

(125564488L, 125564488L)


In [143]:
y[0] = 4 # modyfikuję y

print(x) # a zmienia się x...

[4, 2, 3]


## Funkcja *copy*

In [144]:
from copy import copy

x = [1, 2, 3] # utwórz obiekt typu list
y = copy(x)  # stwórz kopię tego obiektu (w pythonie 3 wystarczy x.copy() )

print(id(x), id(y)) # teraz są to dwa różne obiekty

y[0] = 4 # modyfikuję y
print(x) # i x już się nie zmienia

(110906120L, 117200328L)
[1, 2, 3]
